### ISSUE TITLE
Convert project license to MIT for consistency with other Ring projects

### ISSUE THREAD

**Issue by weavejester** [weavejester/ring-mock#12]
I'd like to make Ring-Mock an official Ring library, but for consistency's sake I'd like to change Ring-Mock's license from EPL to MIT.

@aredington, @neatonk, @timewald, @glenjamin and @senior, could I get each of your permissions to release your additions to Ring Mock under the MIT license?

(I was originally intending to coordinate this via email, but not everyone involved has a public email, so my apologies for the duplication, @senior.)

**Comment by neatonk** [comment]
Ok by me.

**Comment by glenjamin** [comment]
Ok by me too

**Comment by senior** [comment]
I'm fine with the change.

**Comment by aredington** [comment]
I enthusiastically endorse MIT licensing ring-mock.

**Comment by timewald** [comment]
Fine by me.

**Comment by weavejester** [comment]
Thanks very much :)
